pkgname: mocks
template: testify
mockname: "{{.InterfaceName}}"
filename: "{{snakecase .InterfaceName}}.go"
dir: "{{.InterfaceDirRelative}}/mocks"
template-data:
  boilerplate-file: ./tools/config/boilerplate.txt
  with-expecter: true
packages:
  github.com/hantdev/sina/pkg/sdk:
    interfaces:
      SDK:
        config:
          mockname: "SDK"
          filename: "sdk.go"
  github.com/hantdev/sina/re:
    interfaces:
      Repository:
      Service:
      Ticker:
  github.com/hantdev/sina/bootstrap:
    interfaces:
      ConfigRepository:
      ConfigReader:
      Service:
  github.com/hantdev/sina/consumers/notifiers:
    interfaces:
      Service:
      SubscriptionsRepository:
  github.com/hantdev/sina/provision:
    interfaces:
      Service:
